#! /bin/sh

picom --config $HOME/.config/bspwm/picom.conf &
export _JAVA_AWT_WM_NONREPARENTING=1

BSPDIR="$HOME/.config/bspwm"

sxhkd -c $BSPDIR/sxhkdrc &

export PATH="${PATH}:$BSPDIR/scripts"

bspc monitor DP-4 -d 1 2 3 4 5 
bspc monitor DP-2 -d 6 7 8 9 0

bspc config border_width         1
bspc config window_gap           1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true
bspc config presel_feedback true

bspc wm --adopt-orphans

xsetroot -cursor_name left_ptr

#bash ~/.fehbg

bspbar &
