#! /bin/sh
xrdb ${HOME}/.Xresources
killall -q polybar
~/.config/polybar/./launch.sh
pgrep -x sxhkd > /dev/null || sxhkd &
picom --experimental-backends &

bspc monitor DP-0 -d 1 2 3 4
bspc monitor HDMI-0 -d 5 6 7 8

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# bscp desktop -f 1 &
# sleep 1
# exec alacritty -e ranger &
# sleep 0.5
# exec alacritty -e cava &
# exec alacritty -e tty-clock -c -C 5 -s -n &
# sleep 1
# bspc desktop -f 2
# exec code &
# sleep 1
# bscp desktop -f 1 &
# bspc desktop -f 5 &
# exec brave-browser &
# sleep 1
# bspc desktop -f 6
# exec Discord &
# exec telegram-desktop &
# sleep 2
# bspc desktop -f 1 &
# bspc desktop -f 5

#feh --bg-fill $HOME/Downloads/wallpapers/fedora.png & 
feh --bg-fill $HOME/Downloads/wallpapers/purple-sky.jpg & 

# x cursor
xsetroot -cursor_name left_ptr &
