#! /bin/sh

$HOME/.config/polybar/launch.sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-2 -d 1 2 3 4 5
bspc monitor DP-4 -d 6 7 8 9 0

bspc config border_width         0
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config top_padding 0

xsetroot -cursor_name left_ptr

~/.fehbg &
