#!/usr/bin/env bash

DIR="$HOME/.config/bspwm/polybar"

launch_bar() {
  killall -q polybar

  while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

  for mon in $(polybar --list-monitors | cut -d":" -f1); do
    MONITOR=$mon polybar -q main -c "$DIR"/config.ini &
  done
}

launch_bar
